title: Easy Tools
domain: easytools1221.github.io
url: https://easytools1221.github.io

plugins:
    - jekyll-feed
    - jekyll-sitemap

collections:
    tools:
        output: true
        permalink: /:collection/:name