title: Easy Tools
domain: easytools1221.github.io
url: https://easytools1221.github.io

timezone: Asia/Taipei

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-last-modified-at
    - jekyll-seo-tag
    - kramdown

collections:
    tools:
        output: true
        permalink: /:collection/:name

kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge