title: Easy Tools
subtitle: 簡單有趣的小工具提升你的工作效率與生活品質！
domain: easytools1221.github.io
url: https://easytools1221.github.io

timezone: Asia/Taipei

plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-last-modified-at
    - jekyll-seo-tag
    - kramdown

collections:
    tools:
        output: true
        permalink: /tools/:name
    tools_en:
        output: true
        permalink: /en/tools/:name

kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge

last-modified-at:
    date-format: "%Y-%m-%d %H:%M:%S"
