services:
    jekyll:
        image: bretfisher/jekyll-serve
        ports:
            - 11180:4000
            - 35729:35729
        volumes:
            - .:/site:Z
            - .:/srv/jekyll:Z
            - ./vendor/bundle/:/usr/local/bundle:Z
        environment:
            - TZ=Asia/Taipei
        command: jekyll serve --force_polling -H 0.0.0.0
